#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap           20

bspc config normal_border_color "#333333"
bspc config focused_border_color "#aaaaaa"
bspc config presel_feedback_color "#aaaaaa"

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config pointer_motion_interval 16

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a \* rectangle=1920x1080+0+0 center=true

xsetroot -cursor_name left_ptr &

$HOME/.config/polybar/launch.sh &
dunst &

