#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III

bspc config border_width         2
bspc config window_gap           20

bspc config normal_border_color "#333333"
bspc config focused_border_color "#cccccc"

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config pointer_motion_interval 16

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

$HOME/.config/polybar/launch.sh &
